### PR TITLE
Implement an ability of sending messages to the multi-user chat

### PR DESCRIPTION
**Pull request by nikelin**
Before these changes, it was impossible to send message in address of room/group. 

This PR is intended to improve situation by applying minor changes to the `smack.scala.Client` and introducing a new message type - `Messages.SendMultiUserMessage(room, message)`.

### CODE REVIEW

**Comment by mpollmeier** [comment]
can you add a test to `ClientTest` for this please?

**Comment by nikelin** [comment]
Sure

**Comment by mpollmeier** [comment]
looks like your formatter messed up a lot of the codebase in that last commit - can you have a look and only format what you actually added? if there is a need to format the rest of the codebase, that should be a separate commit. 

also, you committed a config change to 'localhost', which means that CI won't be able to run it.

**Comment by nikelin** [comment]
I've reverted the config and the formatting for the code what was not directly affected by my changes. Is it okay know?

**Pull request merged**
